name: Messenger Cron Job

on:
  schedule:
    - cron: '0 15 * * 5'
  workflow_dispatch:

jobs:
  deploy-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Packages
        run: npm install

      - name: Execute Script
        env:
          FACEBOOK_COOKIES: ${{ secrets.FACEBOOK_COOKIES }}
        run: node index.js
