name: "Messenger Reminder: Test 6"

on:
  workflow_dispatch:
    inputs:
      dynamic_message:
        description: 'The message to send'
        required: true
        default: ''

jobs:
  deploy-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm install
      - name: Execute Script
        env:
          FACEBOOK_COOKIES: ${{ secrets.FACEBOOK_COOKIES }}
          PROXY_SERVER: ${{ secrets.PROXY_SERVER }}
          PROXY_USERNAME: ${{ secrets.PROXY_USERNAME }}
          PROXY_PASSWORD: ${{ secrets.PROXY_PASSWORD }}
          CHAT_URL: 'https://www.facebook.com/messages/t/868907569173985/'
          CHAT_MESSAGE: |
            ${{ github.event.inputs.dynamic_message }}
        run: node index.js
